export const imageCards = [
  {
    id: 0,
    img: "microbal.png",
    absoluteImg: 'supply.png',
    alt: "card",
    name1: "Ожирение ч. 2: риски,",
    name2: "генетика, и лечение",
    grey: "9 апрелья \u2022 8 мин",
  },
  {
    id: 1,
    img: "obese.png",
    absoluteImg: 'genetics.png',
    alt: "card",
    name1: "Ожирение ч. 1: причины",
    name2: "и степени заболевания",
    grey: "19 марта \u2022 15 мин",
  },
  {
    id: 2,
    img: "breaking-news.png",
    absoluteImg: 'supply.png',
    alt: "card",
    name1: "Наследственные",
    name2: "заболевания",
    grey: "5 марта \u2022 15 мин",
  },
  {
    id: 3,
    img: "vegetables.png",
    absoluteImg: 'supply.png',
    alt: "card",
    name1: "Фенилкетонунурия или",
    name2: "кому то нельзя есть много",
    grey: "9 апрелья \u2022 8 мин",
  },
  {
    id: 4,
    img: "fast-food.png",
    absoluteImg: 'genetics.png',
    alt: "card",
    name1: "Топ-4 продуктов-",
    name2: "афродизиаков",
    grey: "5 марта \u2022 15 мин",
  },
  {
    id: 5,
    img: "cleanshot.png",
    absoluteImg: 'video.png',
    playBtn: "play-btn.png",
    alt: "card",
    name1: "Почему ДНК-тест сдают",
    name2: "один раз в жизни",
    grey: "5 марта \u2022 15 мин",
  },
  {
    id: 6,
    img: "microbal.png",
    absoluteImg: 'supply.png',
    alt: "card",
    name1: "Ожирение ч. 2: риски,",
    name2: "генетика, и лечение",
    grey: "9 апрелья \u2022 8 мин",
  },
  {
    id: 7,
    img: "obese.png",
    absoluteImg: 'genetics.png',
    alt: "card",
    name1: "Ожирение ч. 1: причины",
    name2: "и степени заболевания",
    grey: "19 марта \u2022 15 мин",
  },
  {
    id: 8,
    img: "breaking-news.png",
    absoluteImg: 'supply.png',
    alt: "card",
    name1: "Наследственные",
    name2: "заболевания",
    grey: "5 марта \u2022 15 мин",
  },
];
